### ISSUE TITLE
渲染字体修改

### ISSUE THREAD

**Issue by Fei-Ni** [lichaozhy/tjucs-airank-2025#16]
（0611新开了一些issue，针对郝老师会上的新要求和指示）

字体层面，郝老师认为并不美观，要用司南上的字体（但具体司南上是啥字体我们也不确定），请修改

**Comment by lichaozhy** [comment]
由当前，
```css
body {
  font-family: "Roboto", "-apple-system", "Helvetica Neue", Helvetica, Arial, sans-serif;
}
```
更新到，
```css
body {
  font-family: "PingFang SC", -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen-Sans, Ubuntu, Cantarell, 'Helvetica Neue', sans-serif;
}
```
